batch_size: 8
data_format: form
seed: 1337
splits: Aachen
max_epochs: 3
num_nodes: 1
precision: bf16
accumulate_grad_batches: null
early_stopping_patience: -1
label_smoothing: 0.0
synthetic_augmentation_proba: 0.4
gradient_clip_val: null
only_lowercase: false
loaded_model: null
learning_rate: 0.0002
d_model: 260
num_layers: 6
nhead: 4
dim_feedforward: 1024
max_seq_len: 700
encoder_name: resnet18
drop_enc: 0.1
drop_dec: 0.1
activ_dec: gelu
